### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by long-long-float** [MichaelSynnott/CilDisassembler#1]
Hi. I'd like to use your good project for a personal project. 
More specifically, I want to modify your code and use it in my project. Of course, I will write a thanks for your project in the document.

However, this project doesn't have a license. If you wouldn't mind, would you add the license? If the added license is not free to modify, I will give up to use your project.

**Comment by MichaelSynnott** [comment]
Hi there!

I've now added an MIT License and you can use the code freely and without restrictions. 

Thanks for your interest in my code.

Regards,

Mike.

**Comment by long-long-float** [comment]
@MichaelSynnott Thank you so much! Your project is very useful for analyzing raw CIL.

**Comment by MichaelSynnott** [comment]
You're very welcome! I'll be very interested in seeing what you do with the code, and I would love it if you would share your project with me when you're ready to do so.

My original code was written in a hurry to serve a specific need, and needs some serious refactoring - to extract methods, shorten classes, add helper classes and generally improve the code. (I also want to rename OpCodeData and make it a Record.)

If I make any improvements, I'll let you know. Feel free to make changes to it yourself and submit a PR,

All the best,

Mike.
